### PR TITLE
docs: Improve readme with installation link and fix extension ID

### PR DESCRIPTION
**Pull request by ffflorian**
While working on #2, I noticed that the extension ID in the readme is wrong and also figured you would appreciate a simpler way of installation.

I also did some formatting changes - feel free to improve or remove them, I added you as a collaborator on [ffflorian/sort-everything](https://github.com/ffflorian/sort-everything) 🙂

### CODE REVIEW

**Comment by bennycode** [comment]
The extension ID wasn't wrong. I was actually just mentioning the Command ID which is "bennycode.sort-everything.sortFile":

image

**Comment by bennycode** [comment]
I will merge your updates though to make use of the nice `kbd` styles.

**Comment by ffflorian** [comment]
> The extension ID wasn't wrong. I was actually just mentioning the Command ID which is "bennycode.sort-everything.sortFile":

Yes, but searching for the command ID in the extension search doesn't work:

**Comment by ffflorian** [comment]
I fixed it in https://github.com/bennycode/sort-everything/pull/6 🙂

**Pull request merged**
